# apiVersion: v1
# kind: Pod
# metadata:
#   name: cluster-pod
#   labels:
#     name: saikiran
#     duty: study
# spec:
#   containers:
#     - name: nginx
#       image: nginx
#       ports:
#         - containerPort: 80
#           name: saikiran-nginx
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   selector:
#     name: saikiran
#     duty: study
#   ports:
#     - port: 80
#       targetPort: saikiran-nginx
#       protocol: TCP
#       name: name-of-service-port

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    environment: dev
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
        name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    environment: dev
    app: frontend
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80 # this port belongs to service
    targetPort: http-web-svc # this port belongs to container