apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    com.project.author: saikiran
    com.project.name: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    