apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
  containers:
    - name: env
      image: nginx
      env:
        - name: author
          value: "saikiran reddy"
        - name: project
          value: "roboshop"
