apiVersion: v1
kind: Pod
metadata:
  name: environment
spec:
  containers:
    - name: env
      image: nginx
      env:
        - name: author
          valueFrom:
            configMapKeyRef: 
              name: configmap
              key: name

        - name: project
          valueFrom:
            configMapKeyRef: 
              name: configmap
              key: course
        - name: duration
          valueFrom:
            configMapKeyRef: 
              name: configmap
              key: duration
          

