apiVersion: v1
kind: Pod
metadata:
  name: refering_all_configmap_data_at_a_time
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        configMapKeyRef: 
          name: configmap
