apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: refering_all_configmap_data_at_a_time
      image: nginx
      envFrom:
        configMapKeyRef: 
          name: configmap
