apiVersion: v1
kind: Pod
metadata:
  name: refering-all-configmap-data-at-a-time
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - configMapRef: 
            name: configmap
