apiVersion: v1
kind: Secret
metadata:
  name: secrets-basic-auth
data:
  username: c2Fpa2lyYW4K
  password: U0Bpa2lyYW4xMQo=
---
apiVersion: v1
kind: Pod
metadata:
  name: refering-all-secrets
spec:
  containers:
  - name: refering-all-secrets
      image: nginx
      envFrom:
      - secretRef: 
            name: secrets-basic-auth

# apiVersion: v1
# kind: Secret
# metadata:
#   name: secret-basic-auth
# data:
#   username: c2l2YWt1bWFyCg==
#   password: YWJjMTIzCg==
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: secret-pod
# spec:
#   containers:
#   - name: secret-pod
#     image: nginx
#     envFrom:
#     - secretRef:
#         name: secret-basic-auth