apiVersion: v1
kind: Secret
metadata:
  name: secrets-basic-auth
data:
  username: c2Fpa2lyYW4K
  password: U0Bpa2lyYW4xMQo=
---
apiVersion: v1
kind: Pod
metadata:
  name: refering-all-secrets
spec:
  containers:
  - name: nginx
      image: nginx
      envFrom:
      - secretRef: 
            name: secrets-basic-auth
