apiVersion: v1
kind: Pod
metadata:
  name: emptydir-example
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /var/log/
  - name: fluentd-sidecar
    image: fluent/fluentd:v1.14.1
    volumeMounts:
    - name: shared-volume
      mountPath: /var/log
  volumes:
  - name: shared-volume
    emptyDir: {}
