apiVersion: v1
kind: Pod
metadata:
  name: emptydir-example
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /var/log/
  - name: fluentd-sidecar
    image: docker.elastic.co/beats/filebeat:7.5.0
    volumeMounts:
    - name: shared-volume
      mountPath: /var/log
  volumes:
  - name: shared-volume
    emptyDir: {}
