apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ebs-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-05ec988a3316c41a0
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: my-ebs-pv  # Replace with your PV name
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    project: roboshop
    tier: web-tier
    component: web
spec:
  # modify replicas according to your case
  replicas: 10
  selector:
    matchLabels:
      project: roboshop
      tier: web-tier
      component: web
  template:
    metadata:
      labels:
        project: roboshop
        tier: web-tier
        component: web
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts: 
          - name: my-volume
            mountPath: /usr/share/nginx/html 
            # subPath: config # this is the key of the configmap
            # readOnly: true
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-ebs-pvc