apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymnt
  labels:
    app: roboshop
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      component: nginx-component
      purpose: practice
      environment: dev
  template:
    metadata:
      labels:
        component: nginx-component
        purpose: practice
        environment: dev
    spec:
      containers:
      - name: nginxdele
        image: nginx:1.14.2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-statefull
spec:
  selector:
    component: nginx-component
    purpose: practice
    environment: dev
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: name-of-service-port
# this clusterIP service is created while explaining the  statefulset